server:
  port: 8080

spring:
  application:
    name: lmf-clients

  datasource:
    url: jdbc:postgresql://localhost:5432/lmf_clients
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: account-group
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    listener:
      ack-mode: manual

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: lmf-clients

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG