apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lmf-bank-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lmf-bank-app

  minReplicas: 2
  maxReplicas: 10

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50