-- Baseline schema, revisado à mão. Ver ADR 0005.
--
-- Reproduz o schema que o Hibernate (ddl-auto) vinha gerando para o PostgreSQL:
-- tipos, nomes de coluna (snake_case), CHECK dos enums (@Enumerated STRING),
-- uniques, índices (@Index) e as duas foreign keys. A partir daqui o schema é
-- explícito e o Hibernate roda apenas como `validate`.

create table account (
    id               bigint         generated by default as identity,
    full_name        varchar(255)   not null,
    document_number  varchar(255)   not null unique,
    birth_date       date           not null,
    mother_name      varchar(255)   not null,
    nationality      varchar(255)   not null check (nationality in ('BRAZILIAN', 'FOREIGN')),
    email            varchar(255)   not null,
    phone            varchar(255)   not null,
    profession       varchar(255)   not null,
    monthly_income   numeric(38, 2) not null,
    account_type     varchar(255)   not null check (account_type in ('CHECKING', 'SAVINGS')),
    account_number   varchar(255)   not null unique,
    agency           varchar(255)   not null,
    accepted_terms   boolean        not null,
    created_at       timestamp(6)   not null,
    updated_at       timestamp(6),
    account_status   varchar(255)   not null check (account_status in ('ACTIVE', 'BLOCKED', 'CLOSED')),
    primary key (id)
);

create table address (
    id            bigint       generated by default as identity,
    account_id    bigint,
    zip_code      varchar(255),
    street        varchar(255),
    neighborhood  varchar(255),
    number        varchar(255),
    complement    varchar(255),
    city          varchar(255),
    state         varchar(255),
    country       varchar(255),
    address_type  varchar(255) check (address_type in ('RESIDENTIAL', 'COMMERCIAL', 'BILLING')),
    primary key (id)
);

create table account_balance (
    id                 bigint         generated by default as identity,
    account_id         bigint         not null unique,
    available_balance  numeric(38, 2) not null,
    blocked_balance    numeric(38, 2) not null,
    total_balance      numeric(38, 2) not null,
    primary key (id)
);

create table transaction (
    id               uuid           not null,
    account_id       bigint         not null,
    type             varchar(255)   not null check (type in ('CREDIT', 'DEBIT')),
    amount           numeric(15, 2) not null,
    status           varchar(255)   not null check (status in ('PENDING', 'COMPLETED', 'FAILED')),
    description      varchar(255)   not null,
    created_at       timestamp(6)   not null,
    transfer_id      uuid,
    idempotency_key  varchar(255)   not null,
    primary key (id),
    constraint uk_transaction_idempotency unique (idempotency_key)
);

create table transfer (
    id               uuid           not null,
    from_account_id  bigint         not null,
    to_account_id    bigint         not null,
    amount           numeric(15, 2) not null,
    status           varchar(255)   not null check (status in ('PENDING', 'COMPLETED', 'FAILED')),
    created_at       timestamp(6)   not null,
    idempotency_key  uuid unique,
    failure_reason   varchar(255),
    primary key (id)
);

create table processed_event (
    event_id      varchar(255) not null,
    processed_at  timestamp(6) not null,
    primary key (event_id)
);

create index idx_transaction_account_created_at on transaction (account_id, created_at);
create index idx_transaction_transfer_id on transaction (transfer_id);
create index idx_transfer_from_account on transfer (from_account_id);
create index idx_transfer_to_account on transfer (to_account_id);

alter table address
    add constraint fk_address_account
    foreign key (account_id) references account;

alter table account_balance
    add constraint fk_account_balance_account
    foreign key (account_id) references account;
