-- Credenciais de login (ADR 0009). Antes disso, /auth/login aceitava qualquer
-- usuário/senha e só emitia o JWT — sem tabela nem verificação nenhuma.
--
-- Semeia um usuário de demonstração para permitir login local/E2E/contrato sem
-- uma tela de cadastro de usuário (fora do escopo do projeto): demo / demo.

create table app_user (
    id             bigint       generated by default as identity,
    username       varchar(255) not null unique,
    password_hash  varchar(255) not null,
    created_at     timestamp(6) not null,
    primary key (id)
);

insert into app_user (username, password_hash, created_at)
values ('demo', '$2a$10$VtMCJr8HPrnh6OCVmPVZzuozLvq4pcp3J91uSQnQXsn2IFKjOd7z6', now());
